### ISSUE TITLE
Cannot install this package in R 4.2.0

### ISSUE THREAD

**Issue by PelikanM400** [VNyaga/NMADAS#1]
Hi Victoria, 
Many thanks for uploading this very helpful package for network meta-analysis of diagnostic accuracy test. I try to install this package in my R 4.2.0 but it returned failure with warning "Error in conformMethod(signature, mnames, fnames, f, fdef, definition) : in method for 'plot' with signature 'x="nmadasfit"': formal arguments (x = "nmadasfit", y = "nmadasfit", ... = "nmadasfit") omitted in the method definition cannot be in the signature". It seems that this package has been removed from CRAN either. 
May I ask if there is any plan for updating this package, or any other way to use this package in the lastest version of R? Your help will be highly appreciated. 
Many thanks!
Best regards, 
Yuelun

**Comment by VNyaga** [comment]
Hi Yeulun,

I have not worked in this project for years.

For now I have no timeline on when I will get back to it but at some point I plan to update it.

It was part of my phd and now I have focused more time in Stata, so my R mind has been dormant such that I will need a huge chunk of time to fix the issues.

Thank you for your email, interest and push;)

Victoria

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: PelikanM400 ***@***.***>
Sent: Friday, June 24, 2022 3:12:08 AM
To: VNyaga/NMADAS ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [VNyaga/NMADAS] Cannot install this package in R 4.2.0 (Issue #1)


Hi Victoria,
Many thanks for uploading this very helpful package for network meta-analysis of diagnostic accuracy test. I try to install this package in my R 4.2.0 but it returned failure with warning "Error in conformMethod(signature, mnames, fnames, f, fdef, definition) : in method for 'plot' with signature 'x="nmadasfit"': formal arguments (x = "nmadasfit", y = "nmadasfit", ... = "nmadasfit") omitted in the method definition cannot be in the signature". It seems that this package has been removed from CRAN either.
May I ask if there is any plan for updating this package, or any other way to use this package in the lastest version of R? Your help will be highly appreciated.
Many thanks!
Best regards,
Yuelun

**Comment by PelikanM400** [comment]
> Hi Yeulun, I have not worked in this project for years. For now I have no timeline on when I will get back to it but at some point I plan to update it. It was part of my phd and now I have focused more time in Stata, so my R mind has been dormant such that I will need a huge chunk of time to fix the issues. Thank you for your email, interest and push;) Victoria Get Outlook for Android<https://aka.ms/AAb9ysg>
> […](#)
> ________________________________ From: PelikanM400 ***@***.***> Sent: Friday, June 24, 2022 3:12:08 AM To: VNyaga/NMADAS ***@***.***> Cc: Subscribed ***@***.***> Subject: [VNyaga/NMADAS] Cannot install this package in R 4.2.0 (Issue #1) Hi Victoria, Many thanks for uploading this very helpful package for network meta-analysis of diagnostic accuracy test. I try to install this package in my R 4.2.0 but it returned failure with warning "Error in conformMethod(signature, mnames, fnames, f, fdef, definition) : in method for 'plot' with signature 'x="nmadasfit"': formal arguments (x = "nmadasfit", y = "nmadasfit", ... = "nmadasfit") omitted in the method definition cannot be in the signature". It seems that this package has been removed from CRAN either. May I ask if there is any plan for updating this package, or any other way to use this package in the lastest version of R? Your help will be highly appreciated. Many thanks! Best regards, Yuelun — Reply to this email directly, view it on GitHub<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVNyaga%2FNMADAS%2Fissues%2F1&data=05%7C01%7C%7Caa229a96a32541ea6b4808da557e8fd9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637916299303974504%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=slP5lcxvkGBDZPvcDjFvs8km88oapE51vygSC0Hu5Ro%3D&reserved=0>, or unsubscribe<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADZUX5PRQR6YEQQ2KX4P47TVQUDORANCNFSM5ZWFGVHA&data=05%7C01%7C%7Caa229a96a32541ea6b4808da557e8fd9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637916299304130737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0ludCT%2BIZ%2Bd4c6HcPaZ0SWQODTAd1mq97d2LFq7PGZA%3D&reserved=0>. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Hi Victoria, 
Many thanks for your reply. Hope to see the updated package soon. 😀
All the best, 
Yuelun
